Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 8080, host: 8080 # Tomcatポート
  config.vm.network "forwarded_port", guest: 3306, host: 3307 # MySQLポート
  config.vm.synced_folder ".", "/home/vagrant/kintai"
  config.vm.provision "shell", path: "setup.sh"
  config.vbguest.auto_update = false
end
